# Generated by Django 3.2.6 on 2021-08-31 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0004_remove_item_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='orgbranch',
        ),
        migrations.AddField(
            model_name='item',
            name='location',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='eye.location'),
            preserve_default=False,
        ),
    ]
