# Generated by Django 3.2.6 on 2021-08-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0008_itemmodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Reserved',
            field=models.BooleanField(default=False),
        ),
    ]
