# Generated by Django 3.2.6 on 2021-08-31 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0009_item_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eye.itemtype'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eye.location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='model',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='eye.itemmodel'),
        ),
        migrations.AlterField(
            model_name='orgbranch',
            name='address',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
