# Generated by Django 3.2.6 on 2021-08-31 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0011_alter_item_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eye.itemtype'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eye.location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eye.itemmodel'),
        ),
    ]
