# Generated by Django 2.2.26 on 2022-04-26 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0013_auto_20220426_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='orgbranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye.Orgbranch'),
        ),
    ]
