# Generated by Django 2.2.26 on 2022-05-13 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0015_auto_20220426_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='served',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='orgbranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye.Orgbranch'),
        ),
    ]
