# Generated by Django 2.2.26 on 2022-08-09 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0018_auto_20220805_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='location',
            name='orgbranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye.Orgbranch'),
        ),
    ]
