# Generated by Django 2.2.26 on 2022-08-24 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0019_auto_20220809_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='orgbranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye.Orgbranch'),
        ),
        migrations.CreateModel(
            name='InfoPrinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qprints', models.PositiveIntegerField(blank=True)),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye.Item')),
            ],
        ),
    ]
