# Generated by Django 2.2.26 on 2022-08-25 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0020_auto_20220824_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='orgbranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye.Orgbranch'),
        ),
        migrations.CreateModel(
            name='InfoUPS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replace_date', models.DateTimeField(blank=True)),
                ('test_date', models.DateTimeField(blank=True)),
                ('test_result', models.CharField(blank=True, max_length=1000)),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye.Item')),
            ],
        ),
    ]
