# Generated by Django 2.2.26 on 2022-08-25 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0021_auto_20220825_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoups',
            name='replace_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infoups',
            name='test_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='orgbranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye.Orgbranch'),
        ),
    ]
