# Generated by Django 2.2.26 on 2022-08-25 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0022_auto_20220825_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='orgbranch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye.Orgbranch'),
        ),
        migrations.CreateModel(
            name='InfoPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateTimeField(blank=True, null=True)),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eye.Item')),
            ],
        ),
    ]
